/***** languages.js *****/
const translations = {
  en: {
    appTitle:"GradeCast Educational Assessment Predictor Platform (ANN+IRT)",
    toc:"Contents",
    tocUpload:"Upload & Mapping",
    tocFeatureSel:"Feature Selection",
    tocConfig:"Model Config & Validation",
    tocTrain:"Training & Progress",
    tocResults:"Results",
    tocPredict:"Prediction",
    tocIRT:"IRT Calibration",
    sectionUpload:"1. Upload & Column Mapping",
    itemCsvTitle:"Item Descriptive CSV",
    itemCsvDesc:"Include: ItemID, Construct, Format ...",
    columnMapping:"Column Mapping",
    itemIdCol:"Item ID Column",
    scoreCsvTitle:"Student Responses CSV",
    scoreCsvDesc:"Long: (StudentID, ItemID, Score). Wide: row=student, columns=items.",
    studentIdCol:"Student ID Column",
    scoreFormat:"Score Format",
    formatLong:"Long: StudentID/ItemID/Score",
    formatWide:"Wide: row=student, cols=items",
    scoreCol:"Score Column (Long)",
    wideItemCols:"Wide Item Columns (multi-select)",
    loadedItemFile:"Item file:",
    loadedScoreFile:"Score file:",
    sectionFeatures:"2. Feature Selection (for ANN)",
    featureHint:"Choose which columns from the Item CSV participate in the model, and set encoding type.",
    sectionConfig:"3. Model Structure & Validation",
    modelStructTitle:"Model Structure",
    batchSize:"Batch Size",
    learningRate:"Learning Rate",
    epochs:"Epochs",
    hiddenLayers:"Hidden Layers",
    addLayer:"+ Add Layer",
    validationTitle:"Validation Configs (add more)",
    validationMethod:"Validation Method",
    holdoutOption:"Holdout (Train/Test Split)",
    loocvOption:"LOOCV (Leave-One-Out)",
    trainRatio:"Train Ratio (%)",
    addValidation:"+ Add Validation",
    sectionTrain:"4. Start Training",
    startTraining:"Start Training",
    progressTraining:"Training (Run {current}/{total}) - {method}",
    progressEpoch:"Run {current}/{total} - Epoch {epoch}/{epochs}",
    progressLOOCV:"Run {current}/{total} - Processed {done}/{totalSamples} samples",
    progressComplete:"Training complete",
    sectionResults:"5. Training Results",
    exportTestCSV:"Export Test Predictions CSV",
    resultHoldout:"Holdout (Training {trainPct}% / Testing {testPct}%)",
    resultLoocv:"LOOCV (Leave-One-Out Cross-Validation)",
    MAE:"MAE (Mean Absolute Error)",
    MSE:"MSE (Mean Squared Error)",
    RMSE:"RMSE (Root Mean Squared Error)",
    R2:"R² (Coefficient of Determination)",
    trainingLoss:"Training Loss",
    validationLoss:"Validation Loss",
    epochAxis:"Epoch",
    lossAxis:"Loss",
    actualVsPred:"Predicted vs Actual",
    idealLine:"Ideal (Y=X)",
    actualAxis:"Actual",
    predictedAxis:"Predicted",
    sectionPredict:"6. Predict New Items",
    predictFileTitle:"Upload new Item Descriptive CSV (same structure)",
    runPredict:"Run Prediction",
    exportPredictCSV:"Export Prediction CSV",
    predictSummary:"Predicted pairs",
    sectionIRT:"7. IRT Calibration & Wright Map",
    exportIRTCSV:"Export IRT Table CSV",
    // alerts
    needUpload:"Please upload both CSVs first.",
    chooseItemMapping:"Please map ItemID.",
    chooseStudentCol:"Please choose StudentID column.",
    chooseLongCols:"Please choose ItemID & Score columns for long format.",
    chooseWideCols:"Please choose item columns for wide format.",
    noValidSamples:"No valid samples after mapping.",
    noValidationAlert:"Please add at least one validation method.",
    trainFirst:"Please train (holdout) to keep a model first.",
    choosePredictFile:"Please upload predict item CSV."
  },
  "zh-CN": {
    appTitle:"GradeCast 教育评估预测平台（ANN+IRT）",
    toc:"功能目录",
    tocUpload:"上传 & 列映射",
    tocFeatureSel:"特征选择",
    tocConfig:"模型配置 & 验证方案",
    tocTrain:"训练 & 进度",
    tocResults:"结果",
    tocPredict:"预测",
    tocIRT:"IRT 校准",
    sectionUpload:"1. 上传数据与列映射",
    itemCsvTitle:"Item 描述信息 CSV",
    itemCsvDesc:"包含：ItemID、Construct、Format 等等。",
    columnMapping:"列映射",
    itemIdCol:"Item ID 列",
    scoreCsvTitle:"学生作答成绩 CSV",
    scoreCsvDesc:"长表：StudentID, ItemID, Score；宽表：行=学生，列=题目。",
    studentIdCol:"Student ID 列",
    scoreFormat:"成绩格式",
    formatLong:"长表：StudentID/ItemID/Score",
    formatWide:"宽表：行=学生，列=题号",
    scoreCol:"Score 列（长表）",
    wideItemCols:"宽表 Item 列（多选）",
    loadedItemFile:"Item 文件：",
    loadedScoreFile:"成绩 文件：",
    sectionFeatures:"2. 特征选择（参与 ANN）",
    featureHint:"从 Item CSV 里选择要参与建模的列，并设置编码类型。",
    sectionConfig:"3. 模型结构 & 验证",
    modelStructTitle:"模型结构",
    batchSize:"批量大小",
    learningRate:"学习率",
    epochs:"训练轮数",
    hiddenLayers:"隐藏层",
    addLayer:"+ 添加隐藏层",
    validationTitle:"验证方案（可添加多个）",
    validationMethod:"验证方法",
    holdoutOption:"拆分验证 (Holdout)",
    loocvOption:"留一验证 (LOOCV)",
    trainRatio:"训练比例 (%)",
    addValidation:"+ 添加验证方案",
    sectionTrain:"4. 开始训练",
    startTraining:"开始训练",
    progressTraining:"训练中 (配置 {current}/{total}) - {method}",
    progressEpoch:"配置 {current}/{total} - 第 {epoch}/{epochs} 轮",
    progressLOOCV:"配置 {current}/{total} - 已处理 {done}/{totalSamples} 个样本",
    progressComplete:"训练完成",
    sectionResults:"5. 训练结果",
    exportTestCSV:"导出测试集预测 CSV",
    resultHoldout:"拆分验证 (训练 {trainPct}% / 测试 {testPct}%)",
    resultLoocv:"留一验证 (LOOCV)",
    MAE:"MAE（平均绝对误差）",
    MSE:"MSE（均方误差）",
    RMSE:"RMSE（均方根误差）",
    R2:"R²（决定系数）",
    trainingLoss:"训练损失",
    validationLoss:"验证损失",
    epochAxis:"轮次",
    lossAxis:"损失",
    actualVsPred:"预测 vs 实际",
    idealLine:"理想线 (Y=X)",
    actualAxis:"实际值",
    predictedAxis:"预测值",
    sectionPredict:"6. 新题预测",
    predictFileTitle:"上传新的 Item 描述 CSV（结构一致）",
    runPredict:"运行预测",
    exportPredictCSV:"导出预测 CSV",
    predictSummary:"预测（学生×题目）组合数",
    sectionIRT:"7. IRT 校准 & Wright Map",
    exportIRTCSV:"导出 IRT 表格 CSV",
    // alerts
    needUpload:"请先上传两个 CSV 文件。",
    chooseItemMapping:"请先选择 ItemID 列。",
    chooseStudentCol:"请选择 StudentID 列。",
    chooseLongCols:"长表需选择 ItemID 与 Score 列。",
    chooseWideCols:"宽表需选择题目列（多选）。",
    noValidSamples:"列映射后无有效样本。",
    noValidationAlert:"请至少添加一个验证方案。",
    trainFirst:"请先用 Holdout 训练得到模型。",
    choosePredictFile:"请上传用于预测的 Item 描述 CSV。"
  },
  "zh-TW": {
    appTitle:"GradeCast 教育評估預測平台 （ANN+IRT）",
    toc:"功能目錄",
    tocUpload:"上傳 & 欄位對應",
    tocFeatureSel:"特徵選擇",
    tocConfig:"模型配置 & 驗證方案",
    tocTrain:"訓練 & 進度",
    tocResults:"結果",
    tocPredict:"預測",
    tocIRT:"IRT 校準",
    sectionUpload:"1. 上傳資料與欄位對應",
    itemCsvTitle:"Item 描述資訊 CSV",
    itemCsvDesc:"包含：ItemID、Construct、Format 等等。",
    columnMapping:"欄位對應",
    itemIdCol:"Item ID 欄",
    scoreCsvTitle:"學生作答成績 CSV",
    scoreCsvDesc:"長表：StudentID, ItemID, Score；寬表：列=學生，欄=題目。",
    studentIdCol:"Student ID 欄",
    scoreFormat:"成績格式",
    formatLong:"長表：StudentID/ItemID/Score",
    formatWide:"寬表：列=學生，欄=題號",
    scoreCol:"Score 欄（長表）",
    wideItemCols:"寬表 Item 欄（多選）",
    loadedItemFile:"Item 檔案：",
    loadedScoreFile:"成績 檔案：",
    sectionFeatures:"2. 特徵選擇（參與 ANN）",
    featureHint:"從 Item CSV 中勾選參與建模的欄位，並設定編碼類型。",
    sectionConfig:"3. 模型結構 & 驗證",
    modelStructTitle:"模型結構",
    batchSize:"批次大小",
    learningRate:"學習率",
    epochs:"訓練輪數",
    hiddenLayers:"隱藏層",
    addLayer:"+ 新增隱藏層",
    validationTitle:"驗證方案（可新增多個）",
    validationMethod:"驗證方法",
    holdoutOption:"拆分驗證 (Holdout)",
    loocvOption:"留一驗證 (LOOCV)",
    trainRatio:"訓練比例 (%)",
    addValidation:"+ 新增驗證方案",
    sectionTrain:"4. 開始訓練",
    startTraining:"開始訓練",
    progressTraining:"訓練中 (配置 {current}/{total}) - {method}",
    progressEpoch:"配置 {current}/{total} - 第 {epoch}/{epochs} 輪",
    progressLOOCV:"配置 {current}/{total} - 已處理 {done}/{totalSamples} 個樣本",
    progressComplete:"訓練完成",
    sectionResults:"5. 訓練結果",
    exportTestCSV:"匯出測試集預測 CSV",
    resultHoldout:"拆分驗證 (訓練 {trainPct}% / 測試 {testPct}%)",
    resultLoocv:"留一驗證 (LOOCV)",
    MAE:"MAE（平均絕對誤差）",
    MSE:"MSE（均方誤差）",
    RMSE:"RMSE（均方根誤差）",
    R2:"R²（決定係數）",
    trainingLoss:"訓練損失",
    validationLoss:"驗證損失",
    epochAxis:"輪次",
    lossAxis:"損失",
    actualVsPred:"預測 vs 實際",
    idealLine:"理想線 (Y=X)",
    actualAxis:"實際值",
    predictedAxis:"預測值",
    sectionPredict:"6. 新題預測",
    predictFileTitle:"上傳新的 Item 描述 CSV（結構一致）",
    runPredict:"執行預測",
    exportPredictCSV:"匯出預測 CSV",
    predictSummary:"預測（學生×題目）組合數",
    sectionIRT:"7. IRT 校準 & Wright Map",
    exportIRTCSV:"匯出 IRT 表格 CSV",
    // alerts
    needUpload:"請先上傳兩個 CSV。",
    chooseItemMapping:"請先選擇 ItemID 欄。",
    chooseStudentCol:"請選擇 StudentID 欄。",
    chooseLongCols:"長表需選擇 ItemID 與 Score 欄。",
    chooseWideCols:"寬表需選擇題目欄（多選）。",
    noValidSamples:"欄位對應後沒有有效樣本。",
    noValidationAlert:"請至少新增一個驗證方案。",
    trainFirst:"請先以 Holdout 訓練保留模型。",
    choosePredictFile:"請上傳用於預測的 Item 描述 CSV。"
  }
};
