/***** languages.js *****/
const translations = {
  "en": {
    // 页面标题和按钮
    "appTitle": "GradeCast Educational Assessment Platform",
    "startTraining": "Start Training",
    "addFeature": "Add Feature",
    "addValidation": "Add Validation",
    "featureConfigTitle": "Model Feature Configuration",
    "structureConfigTitle": "Model Structure Configuration",
    "validationConfigTitle": "Validation Configurations",
    "resultsTitle": "Training Results",
    // 特征配置占位符
    "featurePlaceholder": "Feature name",
    // 模型结构配置标签
    "hiddenNeurons": "Hidden Neurons",
    "epochs": "Epochs",
    "batchSize": "Batch Size",
    "learningRate": "Learning Rate",
    "activationFunc": "Activation Function",
    // 激活函数选项
    "reluOption": "ReLU (Rectified Linear Unit)",
    "sigmoidOption": "Sigmoid (Logistic)",
    "tanhOption": "Tanh (Hyperbolic Tangent)",
    // 验证配置标签
    "validationMethod": "Validation Method",
    "trainRatio": "Train Ratio (%)",
    // 验证方法选项
    "holdoutOption": "Holdout (Train/Test Split)",
    "loocvOption": "LOOCV (Leave-One-Out)",
    // 指标名称
    "MAE": "MAE (Mean Absolute Error)",
    "MSE": "MSE (Mean Squared Error)",
    "RMSE": "RMSE (Root Mean Squared Error)",
    "R2": "R² (Coefficient of Determination)",
    // 图表相关
    "trainingLoss": "Training Loss",
    "validationLoss": "Validation Loss",
    "epochAxis": "Epoch",
    "lossAxis": "Loss",
    "actualVsPred": "Predicted vs Actual",
    "idealLine": "Ideal (Y = X)",
    "actualAxis": "Actual",
    "predictedAxis": "Predicted",
    // 结果标题模板
    "resultHoldout": "Holdout (Training {trainPct}% / Testing {testPct}%)",
    "resultLoocv": "LOOCV (Leave-One-Out Cross-Validation)",
    // 进度文本
    "progressUploading": "Uploading file...",
    "uploadComplete": "File loaded",
    "uploadError": "File upload error",
    "progressTraining": "Training (Run {current}/{total})...",
    "progressEpoch": "Run {current}/{total} - Epoch {epoch}/{epochs}",
    "progressLOOCV": "Run {current}/{total} - Processed {done}/{totalSamples} samples",
    "progressComplete": "Training complete",
    // 提示信息
    "noFileAlert": "Please upload a data file first.",
    "noFeatureAlert": "Please add at least one feature.",
    "noValidationAlert": "Please add at least one validation method."
  },
  "zh-CN": {
    "appTitle": "GradeCast 教育评估平台",
    "startTraining": "开始训练",
    "addFeature": "添加特征",
    "addValidation": "添加验证方案",
    "featureConfigTitle": "模型特征配置",
    "structureConfigTitle": "模型结构配置",
    "validationConfigTitle": "验证方式配置",
    "resultsTitle": "训练结果",
    "featurePlaceholder": "输入特征名称",
    "hiddenNeurons": "隐藏层神经元",
    "epochs": "训练轮数",
    "batchSize": "批量大小",
    "learningRate": "学习率",
    "activationFunc": "激活函数",
    "reluOption": "ReLU（线性整流）",
    "sigmoidOption": "Sigmoid（S型函数）",
    "tanhOption": "Tanh（双曲正切）",
    "validationMethod": "验证方法",
    "trainRatio": "训练比例 (%)",
    "holdoutOption": "拆分验证 (Holdout)",
    "loocvOption": "留一验证 (LOOCV)",
    "MAE": "MAE（平均绝对误差）",
    "MSE": "MSE（均方误差）",
    "RMSE": "RMSE（均方根误差）",
    "R2": "R²（决定系数）",
    "trainingLoss": "训练损失",
    "validationLoss": "验证损失",
    "epochAxis": "轮次",
    "lossAxis": "损失",
    "actualVsPred": "预测值 vs 实际值",
    "idealLine": "理想线 (Y = X)",
    "actualAxis": "实际值",
    "predictedAxis": "预测值",
    "resultHoldout": "拆分验证 (训练 {trainPct}% / 测试 {testPct}%)",
    "resultLoocv": "留一验证 (LOOCV)",
    "progressUploading": "文件上传中...",
    "uploadComplete": "文件读取完成",
    "uploadError": "文件上传错误",
    "progressTraining": "训练中 (配置 {current}/{total})...",
    "progressEpoch": "配置 {current}/{total} - 第 {epoch}/{epochs} 轮",
    "progressLOOCV": "配置 {current}/{total} - 已处理 {done}/{totalSamples} 个样本",
    "progressComplete": "训练完成",
    "noFileAlert": "请先上传数据文件。",
    "noFeatureAlert": "请添加至少一个特征。",
    "noValidationAlert": "请添加至少一种验证方式。"
  },
  "zh-TW": {
    "appTitle": "GradeCast 教育評估平台",
    "startTraining": "開始訓練",
    "addFeature": "新增特徵",
    "addValidation": "新增驗證方案",
    "featureConfigTitle": "模型特徵配置",
    "structureConfigTitle": "模型結構配置",
    "validationConfigTitle": "驗證方式配置",
    "resultsTitle": "訓練結果",
    "featurePlaceholder": "輸入特徵名稱",
    "hiddenNeurons": "隱藏層神經元",
    "epochs": "訓練輪數",
    "batchSize": "批次大小",
    "learningRate": "學習率",
    "activationFunc": "激活函數",
    "reluOption": "ReLU（線性整流）",
    "sigmoidOption": "Sigmoid（S型函數）",
    "tanhOption": "Tanh（雙曲正切）",
    "validationMethod": "驗證方法",
    "trainRatio": "訓練比例 (%)",
    "holdoutOption": "拆分驗證 (Holdout)",
    "loocvOption": "留一驗證 (LOOCV)",
    "MAE": "MAE（平均絕對誤差）",
    "MSE": "MSE（均方誤差）",
    "RMSE": "RMSE（均方根誤差）",
    "R2": "R²（決定係數）",
    "trainingLoss": "訓練損失",
    "validationLoss": "驗證損失",
    "epochAxis": "輪次",
    "lossAxis": "損失",
    "actualVsPred": "預測值 vs 實際值",
    "idealLine": "理想線 (Y = X)",
    "actualAxis": "實際值",
    "predictedAxis": "預測值",
    "resultHoldout": "拆分驗證 (訓練 {trainPct}% / 測試 {testPct}%)",
    "resultLoocv": "留一驗證 (LOOCV)",
    "progressUploading": "檔案上傳中...",
    "uploadComplete": "檔案載入完成",
    "uploadError": "檔案上傳錯誤",
    "progressTraining": "訓練中 (配置 {current}/{total})...",
    "progressEpoch": "配置 {current}/{total} - 第 {epoch}/{epochs} 輪",
    "progressLOOCV": "配置 {current}/{total} - 已處理 {done}/{totalSamples} 個樣本",
    "progressComplete": "訓練完成",
    "noFileAlert": "請先上傳資料檔案。",
    "noFeatureAlert": "請添加至少一個特徵。",
    "noValidationAlert": "請添加至少一種驗證方式。"
  }
};
